### ISSUE TITLE
微博更新大改版，能否更新最新版微博爬虫，不胜感激

### ISSUE THREAD

**Issue by zhyy-air** [srx-2000/spider_collection#14]

**Comment by srx-2000** [comment]
嗯嗯，可以的，因为最近在忙考研的事情，可能这个新版的微博要到一月份才能更新出来了，如果题主不着急的话，到时候更出来了我会在这个issue下给你回复的

**Comment by srx-2000** [comment]
现已更新，同时还做了一些小调整，如运行中出现bug，可以在这个issue中继续提出，我会及时修复的
