### ISSUE TITLE
知乎回答爬虫漏爬的BUG

### ISSUE THREAD

**Issue by TanXinjiang** [srx-2000/spider_collection#20]
您好，使用您的知乎回答爬虫时发现会漏爬前二十个回答，应该是zhihu_answer.py 第51行定义now=0导致的，改成now=0-limit就好了

**Comment by srx-2000** [comment]
感谢你的建议，现已将该bug修复。

**Comment by Owenxu0510** [comment]
你好 这个问题好像没有完全修复

zhihu_answer.py 的第58行循环：
for i in range(0, total_num // limit):

也就是说当该回答的问题数total_num小于limit时，是不会进行爬取的

建议将第139行
result_dict = self.get_answer(question_id, limit=20)
改为
result_dict = self.get_answer(question_id, limit=min(self.get_total(question_id), 20))
