### ISSUE TITLE
知乎API v4现在还能用嘛

### ISSUE THREAD

**Issue by polgry** [srx-2000/spider_collection#22]
**具体项目**
【e.g. 知乎用户爬虫】

**bug描述**
清晰简短的描述bug

**bug复现步骤**
1. ...
2. ...

**报错信息**
请贴出完整的报错信息

**系统环境**
 - 操作系统: Windows10
 - ide: pycharm
 - pyhon版本: 3.7.3

**其他**
其余相关描述或内容

**Comment by srx-2000** [comment]
嗯，可以的，我昨天才测过问答的爬虫代码
