### ISSUE TITLE
请问知乎爬虫项目有没有安装运行教程，在部署运行过程中遇到了一些问题比如ValueError: substring not found这种

### ISSUE THREAD

**Issue by qianlongxiao** [srx-2000/spider_collection#23]
**具体项目**
【e.g. 知乎用户爬虫】

**bug描述**
清晰简短的描述bug

**bug复现步骤**
1. ...
2. ...

**报错信息**
请贴出完整的报错信息

**系统环境**
 - 操作系统: Windows10
 - ide: pycharm
 - pyhon版本: 3.7.3

**其他**
其余相关描述或内容

**Comment by srx-2000** [comment]
嗯？具体是用户数据爬虫还是问答爬虫，请贴出具体完整的报错信息

**Comment by qianlongxiao** [comment]
![image](https://user-images.githubusercontent.com/51913881/158812497-4dc79a36-31ec-426a-bb2b-fab5e9316dea.png)

**Comment by qianlongxiao** [comment]
> 嗯？具体是用户数据爬虫还是问答爬虫，请贴出具体完整的报错信息

![image](https://user-images.githubusercontent.com/51913881/158812552-541d756e-c20b-4af2-a3c0-d238d8c5ba7f.png)
z这样的错误不知道怎么处理

**Comment by qianlongxiao** [comment]
> 嗯？具体是用户数据爬虫还是问答爬虫，请贴出具体完整的报错信息

如果有时间的话能加一下联系方式沟通吗？

**Comment by qianlongxiao** [comment]
> > 嗯？具体是用户数据爬虫还是问答爬虫，请贴出具体完整的报错信息
> 
> ![image](https://user-images.githubusercontent.com/51913881/158812552-541d756e-c20b-4af2-a3c0-d238d8c5ba7f.png) z这样的错误不知道怎么处理

问答爬虫的报错

**Comment by srx-2000** [comment]
> 爬虫的报错

嗯.....这个问题我也不太清楚是因为什么，就看报错信息而言，可能是你的一个临时js文件中的变量发生了问题，应该是execjs运行时发生了冲突，可以找到该文件以及，并查看其第一行61个字符的位置具体发生了什么错误。

**Comment by qianlongxiao** [comment]
您当初使用的配置环境是怎么样的呢？运行这个爬虫时是不是强制要求PyYAML版本和PyExecJS版本了？





> can't comment at this time.

**Comment by srx-2000** [comment]
> can't comment at this time.

嗯....其他版本的库我暂时没有测试过，我使用的库的版本就是requirements中对应的两个库的版本，你可以使用上面的版本试试看

**Comment by sunshineandleaves** [comment]
> > can't comment at this time.
> 
> 嗯....其他版本的库我暂时没有测试过，我使用的库的版本就是requirements中对应的两个库的版本，你可以使用上面的版本试试看

使用了上面版本但是问题依然没有解决

**Comment by srx-2000** [comment]
> 上面版本但是问题依然没有解

嗯.....也是同样的错误嘛，我这里刚刚尝试的运行了一下，两个爬虫都还可以运行，我也在网上进行了以下搜索好像也没有人有遇到过这种情况，我怀疑可能是环境有问题，但也不确定

**Comment by qianlongxiao** [comment]
> > 上面版本但是问题依然没有解
> 
> 嗯.....也是同样的错误嘛，我这里刚刚尝试的运行了一下，两个爬虫都还可以运行，我也在网上进行了以下搜索好像也没有人有遇到过这种情况，我怀疑可能是环境有问题，但也不确定

能给一下你的环境配置表嘛？我想参考一下因为这个爬虫能否运行对我很重要

**Comment by qianlongxiao** [comment]
> > 上面版本但是问题依然没有解
> 
> 嗯.....也是同样的错误嘛，我这里刚刚尝试的运行了一下，两个爬虫都还可以运行，我也在网上进行了以下搜索好像也没有人有遇到过这种情况，我怀疑可能是环境有问题，但也不确定

配上一下我的环境图
![image](https://user-images.githubusercontent.com/51913881/158957498-4750bba0-1632-41e1-9404-4999316e35a0.png)

**Comment by qianlongxiao** [comment]
> > > 上面版本但是问题依然没有解
> > 
> > 
> > 嗯.....也是同样的错误嘛，我这里刚刚尝试的运行了一下，两个爬虫都还可以运行，我也在网上进行了以下搜索好像也没有人有遇到过这种情况，我怀疑可能是环境有问题，但也不确定
> 
> 配上一下我的环境图 ![image](https://user-images.githubusercontent.com/51913881/158957498-4750bba0-1632-41e1-9404-4999316e35a0.png)

这个项目用到了那些配置希望可以具体一点比如数据库如何配置的

**Comment by qianlongxiao** [comment]
本项目的url是否过期了，能否分享一下你运行的url值

**Comment by qianlongxiao** [comment]
![image](https://user-images.githubusercontent.com/51913881/158976276-05f5cfc6-56d1-4288-abd9-d9b077ac0a81.png)
请问这个问题你运行时是否接触过，有解决办法吗？

**Comment by qianlongxiao** [comment]
方便加一下联系方式吗，问题有点多

**Comment by srx-2000** [comment]
> 方便加一下联系方式吗，问题有点多

qq：1601684622

**Comment by sunshineandleaves** [comment]
> **具体项目** 【例如知乎用户爬虫】
> 
> **bug描述** 清晰简短的描述bug
> 
> **bug复现步骤**
> 
> 1. ...
> 2. ...
> 
> **报错信息** 请贴出完整的报错信息
> 
> **系统环境**
> 
> * 操作系统： Windows10
> * ide： pycharm
> * pyhon版本： 3.7.3
> 
> **其他** 其余相关描述或内容



> **具体项目** 【例如知乎用户爬虫】
> 
> **bug描述** 清晰简短的描述bug
> 
> **bug复现步骤**
> 
> 1. ...
> 2. ...
> 
> **报错信息** 请贴出完整的报错信息
> 
> **系统环境**
> 
> * 操作系统： Windows10
> * ide： pycharm
> * pyhon版本： 3.7.3
> 
> **其他** 其余相关描述或内容
我帖一下我遇到的问题和解决方法
python版本需要一致，这个python对应的版本是3.7.3，
需要node.js
from spider.ProxyPool import Proxy_pool报错要找到mark dierctory as选中test source root
cooike值可能会遇到空格错误
