### ISSUE TITLE
关于各个URL

### ISSUE THREAD

**Issue by stu-xsy** [srx-2000/spider_collection#25]
请问各个URL如何获取到的，我只能看到回答的URL

**Comment by srx-2000** [comment]
嗯？具体是哪个子项目的url？

**Comment by stu-xsy** [comment]
就是获取知乎答案的URL，即zhihu_answer.py中的url的获得，我只能通过浏览器找到get_answer()函数中的url
同时我好像发现知乎相似答案的id给出的不一定是回答，而是知乎上的文章（并没有answer_id,只是文章号），这也是造成爬虫爬不到的原因吧

**Comment by srx-2000** [comment]
> 就是获取知乎答案的URL，即zhihu_answer.py中的url的获得，我只能通过浏览器找到get_answer()函数中的url 同时我好像发现知乎相似答案的id给出的不一定是回答，而是知乎上的文章（并没有answer_id,只是文章号），这也是造成爬虫爬不到的原因吧

![image](https://user-images.githubusercontent.com/54949399/159838700-28131034-7acf-41e8-af75-2fa2345fe184.png)

知乎问答的那个我是通过上面那个图片里的相关问题递归爬取的，额，我没有仔细研究过他是否会定位到文章，如果是会定位到文章的话，那确实可能会造成爬取失败的问题吧....
