### ISSUE TITLE
代理池

### ISSUE THREAD

**Issue by stu-xsy** [srx-2000/spider_collection#26]
请问代理具体怎么用呢

**Comment by stu-xsy** [comment]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5010): Max retries exceeded with url: /delete/?proxy= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002317DC4B048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by srx-2000** [comment]
我这个代理池的代码只是对[jhao104/proxy_pool](https://github.com/jhao104/proxy_pool)项目的一个封装，使用前需要先clone上述项目，并跑起来之后，就可以接入我封装的这个代码了，具体跑那个项目的流程。其README里面写的很清楚，我在这里就不复述了

**Comment by stu-xsy** [comment]
好的谢谢
