### ISSUE TITLE
知乎爬虫

### ISSUE THREAD

**Issue by zcs0001** [srx-2000/spider_collection#31]
在zhihu_user_info_spider知乎爬虫中，运行spider出现NotADirectoryError: [WinError 267] 目录名称无效。错误
![image](https://user-images.githubusercontent.com/45141382/182004686-cb0abd8b-774e-47ab-91c7-af0e3437de25.png)

**Comment by srx-2000** [comment]
建议优先参考一下这个issue中的解决办法：[#23](https://github.com/srx-2000/spider_collection/issues/23)
