### ISSUE TITLE
现在知乎回答爬虫里的url还好用吗

### ISSUE THREAD

**Issue by zhiyuan-s** [srx-2000/spider_collection#32]
跑了知乎回答遇到这个问题：
<img width="844" alt="Screen Shot 2022-09-06 at 6 52 58 PM" src="https://user-images.githubusercontent.com/112677778/188754316-37dcd52e-0d68-485c-87b4-0c6107fb0e14.png">
感觉是因为130行得到的response是空的？
另外用的url是https://zhihu.com/api/v4/questions/question_id/answers?.....
这种形式的，但是我在开发者选项里看到现在的url似乎是这样的：https://www.zhihu.com/api/v4/questions/question_id/feeds?cursor=.....
不知道是不是知乎又改了？
感谢！

**Comment by srx-2000** [comment]
嗯...知乎确实改了新的接口...现在知乎的那两个爬虫应该暂时都不能使用了，最近这段时间在忙，后面腾出时间，我会整体更新一下的，感谢反馈
