### ISSUE TITLE
知乎的爬虫项目还会更新吗？

### ISSUE THREAD

**Issue by shuliu586** [srx-2000/spider_collection#40]
大佬您好，我仔细看了你昨天发布的知乎加密规则的更新，确实写的十分详细，我这个新手小白也受益匪浅，感谢~

想请问下关于知乎的爬虫项目，大佬之后是否会有更新计划？是这样的，我们是名为知识岛（KnowledgeDAO）的自发项目，目的是希望为中文AI提供高质量训练数据（目前已经有八个数据集，还在计划不断扩充中。。。），项目地址为：https://github.com/shuliu586/AI_Chinese_DataSet_KnowledgeDAO。项目目前还处于早期阶段，目前的计划是想扩充知乎的数据集，万幸找到了您这个项目，所有想问下大佬是否有继续更新知乎爬虫的计划，感谢回复！

**Comment by srx-2000** [comment]
> 大佬您好，我仔细看了你昨天发布的知乎加密规则的更新，确实写的十分详细，我这个新手小白也受益匪浅，感谢~
> 
> 想请问下关于知乎的爬虫项目，大佬之后是否会有更新计划？是这样的，我们是名为知识岛（KnowledgeDAO）的自发项目，目的是希望为中文AI提供高质量训练数据（目前已经有八个数据集，还在计划不断扩充中。。。），项目地址为：[https://github.com/shuliu586/AI_Chinese_DataSet_KnowledgeDAO。项目目前还处于早期阶段，目前的计划是想扩充知乎的数据集，万幸找到了您这个项目，所有想问下大佬是否有继续更新知乎爬虫的计划，感谢回复！](https://github.com/shuliu586/AI_Chinese_DataSet_KnowledgeDAO%E3%80%82%E9%A1%B9%E7%9B%AE%E7%9B%AE%E5%89%8D%E8%BF%98%E5%A4%84%E4%BA%8E%E6%97%A9%E6%9C%9F%E9%98%B6%E6%AE%B5%EF%BC%8C%E7%9B%AE%E5%89%8D%E7%9A%84%E8%AE%A1%E5%88%92%E6%98%AF%E6%83%B3%E6%89%A9%E5%85%85%E7%9F%A5%E4%B9%8E%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E4%B8%87%E5%B9%B8%E6%89%BE%E5%88%B0%E4%BA%86%E6%82%A8%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%EF%BC%8C%E6%89%80%E6%9C%89%E6%83%B3%E9%97%AE%E4%B8%8B%E5%A4%A7%E4%BD%AC%E6%98%AF%E5%90%A6%E6%9C%89%E7%BB%A7%E7%BB%AD%E6%9B%B4%E6%96%B0%E7%9F%A5%E4%B9%8E%E7%88%AC%E8%99%AB%E7%9A%84%E8%AE%A1%E5%88%92%EF%BC%8C%E6%84%9F%E8%B0%A2%E5%9B%9E%E5%A4%8D%EF%BC%81)

我不是很清楚你这里指的更新计划是大批量爬取的脚本嘛，如果是的话，可能不会有这方面的计划了，主要有两个原因，一个是个人大批量高频率的爬取肯定是不太好的，第二个是我个人之前搞过一个多线程爬取的代码，花费了很多精力，但是现在再看之前的那个代码，感觉很多都是无用功，从个人的感受上来说没有一个加密文件接口来的精干好看。
当然，我刚刚发的那个加密脚本本身对外暴露出来的方法应该也算是很简单了，如果你们真的有需要倒是可以在那个接口的基础上自己写一些爬取策略。具体调用时的各种参数更改应该也不是很难，具体的值可以根据你们自己的需求更改。

**Comment by srx-2000** [comment]
> 大佬您好，我仔细看了你昨天发布的知乎加密规则的更新，确实写的十分详细，我这个新手小白也受益匪浅，感谢~
> 
> 想请问下关于知乎的爬虫项目，大佬之后是否会有更新计划？是这样的，我们是名为知识岛（KnowledgeDAO）的自发项目，目的是希望为中文AI提供高质量训练数据（目前已经有八个数据集，还在计划不断扩充中。。。），项目地址为：[https://github.com/shuliu586/AI_Chinese_DataSet_KnowledgeDAO。项目目前还处于早期阶段，目前的计划是想扩充知乎的数据集，万幸找到了您这个项目，所有想问下大佬是否有继续更新知乎爬虫的计划，感谢回复！](https://github.com/shuliu586/AI_Chinese_DataSet_KnowledgeDAO%E3%80%82%E9%A1%B9%E7%9B%AE%E7%9B%AE%E5%89%8D%E8%BF%98%E5%A4%84%E4%BA%8E%E6%97%A9%E6%9C%9F%E9%98%B6%E6%AE%B5%EF%BC%8C%E7%9B%AE%E5%89%8D%E7%9A%84%E8%AE%A1%E5%88%92%E6%98%AF%E6%83%B3%E6%89%A9%E5%85%85%E7%9F%A5%E4%B9%8E%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E4%B8%87%E5%B9%B8%E6%89%BE%E5%88%B0%E4%BA%86%E6%82%A8%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%EF%BC%8C%E6%89%80%E6%9C%89%E6%83%B3%E9%97%AE%E4%B8%8B%E5%A4%A7%E4%BD%AC%E6%98%AF%E5%90%A6%E6%9C%89%E7%BB%A7%E7%BB%AD%E6%9B%B4%E6%96%B0%E7%9F%A5%E4%B9%8E%E7%88%AC%E8%99%AB%E7%9A%84%E8%AE%A1%E5%88%92%EF%BC%8C%E6%84%9F%E8%B0%A2%E5%9B%9E%E5%A4%8D%EF%BC%81)

当然，如果更新计划指的是后续跟进知乎的新加密的话，我这边确实有一些计划，比如加入客户端和js补环境两种别的方式，如果后续知乎那边替换了算法，我这边也会根据自己的能力以及时间看看是否要进一步跟进。
