### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by youzeliang** [srx-2000/spider_collection#43]
**具体项目**
【e.g. 知乎用户爬虫】

**bug描述**
知乎接口报错
{'message': '请求参数异常，请升级客户端后重试。', 'code': 10003}
应该是知乎接口又升级了

**bug复现步骤**
替换了cookie 就报这个。

**报错信息**
请贴出完整的报错信息

**系统环境**
 - 操作系统: macOS
 - ide: pycharm
 - pyhon版本: 3.7.3

**其他**
其余相关描述或内容

**Comment by srx-2000** [comment]
> **具体项目** 【e.g. 知乎用户爬虫】
> 
> **bug描述** 知乎接口报错 {'message': '请求参数异常，请升级客户端后重试。', 'code': 10003} 应该是知乎接口又升级了
> 
> **bug复现步骤** 替换了cookie 就报这个。
> 
> **报错信息** 请贴出完整的报错信息
> 
> **系统环境**
> 
> * 操作系统: macOS
> * ide: pycharm
> * pyhon版本: 3.7.3
> 
> **其他** 其余相关描述或内容

之前的加密过期了，现在的加密可以看项目中的这个[目录](https://github.com/srx-2000/spider_collection/tree/dab641a3a45885b1fcb0fb344088111ed13a1a49/zhihuEncrypt)，可以尝试自己介入一下原先的代码
